POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "username": "JohnDoe",
    "email": "john@example.com",
    "password": "password123"
}

### Login Request
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "john@example.com",
    "password": "password123"
}

### Access Profile (Protected Route)
GET http://localhost:3000/profile
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzA2YTgxMTEyNWEyYzQzMDBhNjIxOWMiLCJ1c2VyTmFtZSI6IkpvaG5Eb2UiLCJpYXQiOjE3Mjg0OTA5MjQsImV4cCI6MTcyODQ5NDUyNH0.aJO1H0AaEkyHjc0KvidBGawp-2dZpFWAShgbD0eMwIw

